/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RacesIndexRouteImport } from './routes/races.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RacesRaceIdRouteImport } from './routes/races.$raceId'
import { Route as CandidatesCandidateIdRouteImport } from './routes/candidates.$candidateId'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as AdminRacesRouteImport } from './routes/admin.races'
import { Route as AdminPositionClaimsRouteImport } from './routes/admin.position-claims'
import { Route as AdminIssuesRouteImport } from './routes/admin.issues'
import { Route as AdminExtractorRouteImport } from './routes/admin.extractor'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as RacesRaceIdIssuesIssueIdRouteImport } from './routes/races.$raceId.issues.$issueId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesIndexRoute = RacesIndexRouteImport.update({
  id: '/races/',
  path: '/races/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RacesRaceIdRoute = RacesRaceIdRouteImport.update({
  id: '/races/$raceId',
  path: '/races/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesCandidateIdRoute = CandidatesCandidateIdRouteImport.update({
  id: '/candidates/$candidateId',
  path: '/candidates/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRacesRoute = AdminRacesRouteImport.update({
  id: '/races',
  path: '/races',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPositionClaimsRoute = AdminPositionClaimsRouteImport.update({
  id: '/position-claims',
  path: '/position-claims',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIssuesRoute = AdminIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExtractorRoute = AdminExtractorRouteImport.update({
  id: '/extractor',
  path: '/extractor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const RacesRaceIdIssuesIssueIdRoute =
  RacesRaceIdIssuesIssueIdRouteImport.update({
    id: '/issues/$issueId',
    path: '/issues/$issueId',
    getParentRoute: () => RacesRaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/extractor': typeof AdminExtractorRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/position-claims': typeof AdminPositionClaimsRoute
  '/admin/races': typeof AdminRacesRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/races/$raceId': typeof RacesRaceIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/races/': typeof RacesIndexRoute
  '/races/$raceId/issues/$issueId': typeof RacesRaceIdIssuesIssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/extractor': typeof AdminExtractorRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/position-claims': typeof AdminPositionClaimsRoute
  '/admin/races': typeof AdminRacesRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/races/$raceId': typeof RacesRaceIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/races': typeof RacesIndexRoute
  '/races/$raceId/issues/$issueId': typeof RacesRaceIdIssuesIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/extractor': typeof AdminExtractorRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/position-claims': typeof AdminPositionClaimsRoute
  '/admin/races': typeof AdminRacesRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/races/$raceId': typeof RacesRaceIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/races/': typeof RacesIndexRoute
  '/races/$raceId/issues/$issueId': typeof RacesRaceIdIssuesIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/methodology'
    | '/reset-password'
    | '/admin/candidates'
    | '/admin/extractor'
    | '/admin/issues'
    | '/admin/position-claims'
    | '/admin/races'
    | '/admin/sources'
    | '/candidates/$candidateId'
    | '/races/$raceId'
    | '/admin/'
    | '/races/'
    | '/races/$raceId/issues/$issueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/methodology'
    | '/reset-password'
    | '/admin/candidates'
    | '/admin/extractor'
    | '/admin/issues'
    | '/admin/position-claims'
    | '/admin/races'
    | '/admin/sources'
    | '/candidates/$candidateId'
    | '/races/$raceId'
    | '/admin'
    | '/races'
    | '/races/$raceId/issues/$issueId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/methodology'
    | '/reset-password'
    | '/admin/candidates'
    | '/admin/extractor'
    | '/admin/issues'
    | '/admin/position-claims'
    | '/admin/races'
    | '/admin/sources'
    | '/candidates/$candidateId'
    | '/races/$raceId'
    | '/admin/'
    | '/races/'
    | '/races/$raceId/issues/$issueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MethodologyRoute: typeof MethodologyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CandidatesCandidateIdRoute: typeof CandidatesCandidateIdRoute
  RacesRaceIdRoute: typeof RacesRaceIdRouteWithChildren
  RacesIndexRoute: typeof RacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/': {
      id: '/races/'
      path: '/races'
      fullPath: '/races/'
      preLoaderRoute: typeof RacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/races/$raceId': {
      id: '/races/$raceId'
      path: '/races/$raceId'
      fullPath: '/races/$raceId'
      preLoaderRoute: typeof RacesRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$candidateId': {
      id: '/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof CandidatesCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/races': {
      id: '/admin/races'
      path: '/races'
      fullPath: '/admin/races'
      preLoaderRoute: typeof AdminRacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/position-claims': {
      id: '/admin/position-claims'
      path: '/position-claims'
      fullPath: '/admin/position-claims'
      preLoaderRoute: typeof AdminPositionClaimsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/issues': {
      id: '/admin/issues'
      path: '/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AdminIssuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/extractor': {
      id: '/admin/extractor'
      path: '/extractor'
      fullPath: '/admin/extractor'
      preLoaderRoute: typeof AdminExtractorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/races/$raceId/issues/$issueId': {
      id: '/races/$raceId/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/races/$raceId/issues/$issueId'
      preLoaderRoute: typeof RacesRaceIdIssuesIssueIdRouteImport
      parentRoute: typeof RacesRaceIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminExtractorRoute: typeof AdminExtractorRoute
  AdminIssuesRoute: typeof AdminIssuesRoute
  AdminPositionClaimsRoute: typeof AdminPositionClaimsRoute
  AdminRacesRoute: typeof AdminRacesRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminExtractorRoute: AdminExtractorRoute,
  AdminIssuesRoute: AdminIssuesRoute,
  AdminPositionClaimsRoute: AdminPositionClaimsRoute,
  AdminRacesRoute: AdminRacesRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RacesRaceIdRouteChildren {
  RacesRaceIdIssuesIssueIdRoute: typeof RacesRaceIdIssuesIssueIdRoute
}

const RacesRaceIdRouteChildren: RacesRaceIdRouteChildren = {
  RacesRaceIdIssuesIssueIdRoute: RacesRaceIdIssuesIssueIdRoute,
}

const RacesRaceIdRouteWithChildren = RacesRaceIdRoute._addFileChildren(
  RacesRaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MethodologyRoute: MethodologyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CandidatesCandidateIdRoute: CandidatesCandidateIdRoute,
  RacesRaceIdRoute: RacesRaceIdRouteWithChildren,
  RacesIndexRoute: RacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
